name: Build and Deploy Docker image to AWS Lightsail

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build Docker image
        run: docker build -t yeltech-ai -f back_end/Dockerfile .

      - name: Tag Docker image
        run: docker tag yeltech-ai:latest 706556827168.dkr.ecr.eu-west-2.amazonaws.com/yeltech-ai:latest

      - name: Push Docker image to AWS Lightsail
        run: |
          aws lightsail push-container-image --service-name yeltech-ai --label latest --image yeltech-ai:latest
